services:
  postgres:
    image: postgres:16
    container_name: sga-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - sga_pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sga_admin -d sga_sentiment"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  sga_pgdata:
    driver: local
